# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bgg 1.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "bgg"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeremiah Lee", "Brett Hardin"]
  s.date = "2015-06-06"
  s.description = "Object-oriented interface for interacting with Boardgamegeek API"
  s.email = "jeremiah.lee@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bgg.gemspec",
    "lib/bgg/game.rb",
    "lib/bgg/link.rb",
    "lib/bgg/request/base.rb",
    "lib/bgg/request/collection.rb",
    "lib/bgg/request/family.rb",
    "lib/bgg/request/guild.rb",
    "lib/bgg/request/hot.rb",
    "lib/bgg/request/plays.rb",
    "lib/bgg/request/search.rb",
    "lib/bgg/request/user.rb",
    "lib/bgg/result/collection.rb",
    "lib/bgg/result/collection_item.rb",
    "lib/bgg/result/collection_item_rank.rb",
    "lib/bgg/result/enumerable.rb",
    "lib/bgg/result/family.rb",
    "lib/bgg/result/guild.rb",
    "lib/bgg/result/hot.rb",
    "lib/bgg/result/hot_item.rb",
    "lib/bgg/result/item.rb",
    "lib/bgg/result/plays.rb",
    "lib/bgg/result/plays_play.rb",
    "lib/bgg/result/search.rb",
    "lib/bgg/result/search_item.rb",
    "lib/bgg/result/user.rb",
    "lib/bgg_api.rb",
    "sample_data/collection.xml",
    "sample_data/guild.xml",
    "sample_data/hot.xml",
    "sample_data/plays.xml",
    "sample_data/search.xml",
    "sample_data/thing?id=10000000&type=boardgame",
    "sample_data/thing?id=29773&type=boardgame",
    "sample_data/thing?id=70512&type=boardgame",
    "sample_data/thing?id=84876&type=boardgame",
    "sample_data/user?name=texasjdl",
    "sample_data/user?name=yyyyyyy",
    "spec/bgg/request/base_spec.rb",
    "spec/bgg/request/collection_spec.rb",
    "spec/bgg/request/family_spec.rb",
    "spec/bgg/request/guild_spec.rb",
    "spec/bgg/request/hot_spec.rb",
    "spec/bgg/request/plays_spec.rb",
    "spec/bgg/request/search_spec.rb",
    "spec/bgg/request/user_spec.rb",
    "spec/bgg/result/collection_item_rank_spec.rb",
    "spec/bgg/result/collection_item_spec.rb",
    "spec/bgg/result/collection_spec.rb",
    "spec/bgg/result/enumerable_spec.rb",
    "spec/bgg/result/family_spec.rb",
    "spec/bgg/result/guild_spec.rb",
    "spec/bgg/result/hot_item_spec.rb",
    "spec/bgg/result/hot_spec.rb",
    "spec/bgg/result/item_spec.rb",
    "spec/bgg/result/plays_play_spec.rb",
    "spec/bgg/result/plays_spec.rb",
    "spec/bgg/result/search_item_spec.rb",
    "spec/bgg/result/search_spec.rb",
    "spec/bgg/result/user_spec.rb",
    "spec/bgg_api_spec.rb",
    "spec/bgg_game_spec.rb",
    "spec/bgg_link_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jemiahlee/bgg"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "object-oriented boardgamegeek api gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.6.1"])
      s.add_runtime_dependency(%q<xml-simple>, ["~> 1.1.1"])
      s.add_development_dependency(%q<bundler>, [">= 1.6.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.7.1"])
      s.add_development_dependency(%q<webmock>, ["~> 1.8.9"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, ["~> 0.3.0"])
      s.add_development_dependency(%q<rake>, ["~> 10.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.8.3"])
      s.add_dependency(%q<nokogiri>, ["~> 1.6.1"])
      s.add_dependency(%q<xml-simple>, ["~> 1.1.1"])
      s.add_dependency(%q<bundler>, [">= 1.6.2"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<simplecov>, ["~> 0.7.1"])
      s.add_dependency(%q<webmock>, ["~> 1.8.9"])
      s.add_dependency(%q<codeclimate-test-reporter>, ["~> 0.3.0"])
      s.add_dependency(%q<rake>, ["~> 10.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.8.3"])
    s.add_dependency(%q<nokogiri>, ["~> 1.6.1"])
    s.add_dependency(%q<xml-simple>, ["~> 1.1.1"])
    s.add_dependency(%q<bundler>, [">= 1.6.2"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<simplecov>, ["~> 0.7.1"])
    s.add_dependency(%q<webmock>, ["~> 1.8.9"])
    s.add_dependency(%q<codeclimate-test-reporter>, ["~> 0.3.0"])
    s.add_dependency(%q<rake>, ["~> 10.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
  end
end

